# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import helloworld_pb2 as proto_dot_helloworld__pb2


class HelloServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_message = channel.unary_unary(
                '/tutorials.HelloServer/get_message',
                request_serializer=proto_dot_helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=proto_dot_helloworld__pb2.HelloResponse.FromString,
                )


class HelloServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_message': grpc.unary_unary_rpc_method_handler(
                    servicer.get_message,
                    request_deserializer=proto_dot_helloworld__pb2.HelloRequest.FromString,
                    response_serializer=proto_dot_helloworld__pb2.HelloResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tutorials.HelloServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HelloServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tutorials.HelloServer/get_message',
            proto_dot_helloworld__pb2.HelloRequest.SerializeToString,
            proto_dot_helloworld__pb2.HelloResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
